def options(opt):
	opt.load('compiler_cxx')

def configure(conf):
	conf.load('conan', tooldir='../..')
	conf.load_conan()
	conf.load('compiler_cxx')

def build(bld):
	bld(
		features = "cxx cxxprogram conan",
		source = "main.cpp",
		use = "sdl",
		target = "app"
	)
